<?php

function cier_block_info() {
  $blocks['cier'] = array(
    'info' => t('Eventos'),
  );

  return $blocks;
}

function cier_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'cier':
      $block['subject'] = t('Eventos');
      $block['content'] = execute_select_query();
    break;
  }
  return $block;
}

function execute_select_query(){
  $output = '';

  $query = db_select('event', 'c')
      ->fields('c');

  $result = $query->execute();

  $output .= get_open_box_container();

  while($record = $result->fetchAssoc()) {
      $output .= get_open_box();
      $output .= $record["name"] . '<br/>';
      $output .= $record["url"] . '<br/>';
      $output .= $record["date"] . '<br/>';
      $output .= $record["hour"] . '<br/>';
      $output .= get_close_box();
  }

  $output .= get_close_box_container();

  return $output;
}

function get_open_box_container(){
  return "<div class='wrapper'>";
}

function get_open_box(){
  return "<div class='box'>";
}

function get_close_box_container(){
  return "</div>";
}

function get_close_box(){
  return "</div>";
}
